### PR TITLE
docs(zh): fix some typo

### PR DESCRIPTION
**Pull request by PatrickChen928**

### CODE REVIEW

**Comment by KimYangOfCat** [comment]
感谢你的校对，大部分都是 英文译中文之后，英文专业词复数的问题，但其实翻译之后不保留复数，是一个翻译风格问题，从中文去理解，这些专业词就已经可以指代一类事物了，所以我没有保留复数，因为在中文语境中没有通过 +s 来体现复数，进而代指一类事物的概念。中文语境中的复数更多是靠量词来体现的，所以这些复数词更好的润色方式，也许是给它们添加一个量词，比如，这些，一些等等。当时翻译时间比较赶，我就没做这些比较细致的润色啦，哈哈， 谢谢你的 review，如果你还有其他意见，欢迎在本 PR 中全部提交，过几天，我再统一 merge 吧！另外，你的头像（莫山山）真不错，我也很喜欢，哈哈！

**Comment by PatrickChen928** [comment]
> 感谢你的校对，大部分都是 英文译中文之后，英文专业词复数的问题，但其实翻译之后不保留复数，是一个翻译风格问题，从中文去理解，这些专业词就已经可以指代一类事物了，所以我没有保留复数，因为在中文语境中没有通过 +s 来体现复数，进而代指一类事物的概念。中文语境中的复数更多是靠量词来体现的，所以这些复数词更好的润色方式，也许是给它们添加一个量词，比如，这些，一些等等。当时翻译时间比较赶，我就没做这些比较细致的润色啦，哈哈， 谢谢你的 review，如果你还有其他意见，欢迎在本 PR 中全部提交，过几天，我再统一 merge 吧！另外，你的头像（莫山山）真不错，我也很喜欢，哈哈！

emmm...复数这个你这么说也没错。我之前的理解是，actions代表的是action的集合，在理解上能和action区分开。action算是一个方法，actions算是这个方法的集合，也就是功能。这个可能就是理解上的差异吧，哈哈哈。

剩下的我今天有时间再继续看看。

（莫山山，yyds～

**Comment by KimYangOfCat** [comment]
Hello， @ChpShy ,我先把这个 PR 合并了，如果你还有其他修改提议，欢迎你提交新的 PR， 如果你没有其他修改意见了，希望能去[我的 PR](https://github.com/vuejs/pinia/pull/1193)  上帮我 approve 一下，非常感谢！

**Comment by josuecv26** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
1615450788, @ron159, @paolouma, @heracek, @rarechit, @fandaosi, @hanx-iao, @s-mies, @yanweibing, @qivhou, @LeinaGray, @Pegasus-E, @yfyyrh, @birthdaysgift, @kevin123274, @justinwash, @codex009, @YooPita, @hartex, @lnsoso, @k1013s, @hypnosophy, @Osil1, @sorairolake, @lonjoy, @liulinhui, @deepserket, @yauri-io, @abdullahwaqar, @A11en0, @ivcpp, @panzhaohui, @nobiit, @hating, @satler-git, @ihor-nahuliak, @baojiaqian, @mvpvg, @tinck, @liomen, @mesondzh, @Strengthyu, @leixy2004, @anviod, @ode233, @jackzheng870, @haroldduan, @WardPearce, @fgmdanny, @ChandlerVer5ccyanxyz, @meows6, @salimbenfarhat, @rastislavcore, @jurajlisiak, @Palhanor, @linhongjun, @AlphaXyXy, @Polve, @xbucd, @digitalrobertlima, @lynther, @pdlwf, @thedvd98, @codingsf, @ThebCCapp, @ahghanbari, @efranelas, @matheusfelipeog, @MrMatrixPL, @kayix, @tk-programmer, @pirate, @mgk99sn, @danielepusceddu, @simsieg, @plamengj, @ryanbwolf, @wiki6, @ruslankonev, @hychen, @onyas, @colsw, @machavia, @lichenysq, @balhaddad, @bambino-boy, @yojeajie, @smmousavi76, @Eeyhan, @horrrt, @sawaYch, @styromaniac, @shaksiper, @leungwensen, @luajk, @LinhHoang8997, @merlijndetovenaar84, @Lovesakura, @maulik-pStarterforward, @xingran521, @rabat, @moveax3, @krystofair, @HyramTang, @GE2Graf19186, @xnicoleisaloser, @zschzen, @leungwensen, @mbelletti, @dylnbk, @Rika321, @AGkite, @andriyor, @radevgit, @baojiaqian, @professorbk, @HXN2, @yuanwenbin5521, @DianaTheCoderess, @vincentbd123, @arbal, @A11en0, @swapnil823, @Cree0618, @yfhk, @Crypto-Spartan, @connorbill, @weedsstars, @techrattt, @flotox, @ALPERDURUKAN, @sumon117, @k3ybladewielder, @tangingw, @Castlenine, @keef1212, @hatamiarash7, @niuwenqi, @suexcxine, @qarth, @hundan2020, @lbinxianchong, @pyrooka, @Gum-Joe, @cndolo, @prashantkhandelwal, @yhoungdev, @weebilatenightz, @RaidoWolf, @momansoury, @ZsoltGergely, @matthewhcz, @Pereira-Araujo, @stuible, @utopfish, @dannyxddd, @ziluoxingjun, @Cale318, @lrdass, @budui, @iemadk, @dwcost, @w1kke, @httppedro, @flavidetosnow, @sjdiego, @1uka, @aijun198600, @Ti-yor, @kylege, @ZegJoker, @willxuecn, @tyoc213, @TzZek, @1229z, @gastonmorixe, @teerawatxxx, @tdkr, @why168, @busyluo, @foyez, @nightmare-rg, @rolodexter, @mcthesw, @nonomal, @tapan288, @jilv220, @IbbyBenali, @justicestorm, @shreyaspapi, @Donaim, @siagrossi, @TokenDance, @Mamu9, @yutimothy666, @PadLex, @justinwashutopfish, @ShiSheng233, @CheezBallzPi, @onanying, @zhoudaqing, @bermanboris, @RobustBody, @hillockgangmemory, @BitToFly, @ismartcoding, @veshitala, @ninjabreakbot, @magicalraccoon, @JZWen, @doomspec, @yuebaiqinghui, @tarupo, @SavanDev, @sinahwz, @matinkaboli, @cainiaocome, @lqzhou123, @radicalized, @fugio, @cyueclone, @lrdass, @coinsky, @SINC-G, @dsyzhao, @lovealan, @dabana, @mohsen-in, @anotherglitchinthematrix, @sirily11, @apurbapathak, @spikespaz, @vloddos, @deyout, @olekhy, @halfnother, @leakira, @simonewebdesign, @piogg, @EInk-JIe, @tudos4, @guohezuzi, @gnknithin, @MinmoTech, @Lynskylate, @xc0derxMendax1989, @gankyui, @sillyzilly, @maragard, @LaelLuo, @Apostle-Abbibas, @Max-Dva4, @msaccelerate, @genikineg, @songproducer, @aleatory-avers, @hafis915, @liaoyijun, @wilbur-yu, @dongchunfeng, @xsj34567, @morristech, @qustavo, @wizcap, @SyXo, @AndreiSva, @andyoknen, @aaronuu, @TomPCurran, @Mohammadimh76, @yashodhank, @bufgix, @pur3miish, @OutThisLife, @cn-kali-team, @akimdi, @mohsenusr, @liesauer, @Priyanshu79, @endframe-inc, @bakkan, @laztb9, @loongdy, @FractalHQ, @ygexe, @devsecur, @comeUpWithItLater, @1229z, @verdinjoshua1982, @PINKONG, @andrewratliff, @maejoux, @BZK44, @zaoying, @davidblitzSpokieKid, @TomZhang1019, @Shokr, @mono424, @wlemuel, @thisssky, @wujunze, @WeiJunFenYou, @neverrop, @borankux, @kckeiks, @din8sh, @kotoko, @deetwelve, @dandisy, @luavixen, @heshenxian1, @doutv, @Littlecowherd, @st-Taku, @Silverteal, @GabeWilson, @hust921, @seanb95531, @Brieuclantivy, @fgmdanny, @CmderQ, @SexyBeast233, @masclown, @MYJN, @shenjun715, @Simon-Jester671, @cangyunye, @miloshavlicek, @54itfan, @awilisch, @eduardconstantin, @olivere, @Riahiamirreza, @bytjn1416124, @emacsenli666, @ayyopb, @raulk, @songsammy, @sezginpak, @seekincs, @ihewro, @KrzysztofKowalski, @Shifaat, @Three-taile-dragon

**Comment by josuecv26** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
akirayamamoto, @arhantsundaram, @premsantosh, @tarasyarema, @guangzhaohui, @ibel001, @T-Raytheon, @38b3eff8, @yao-yi, @longlive77, @nevill, @shasa, @SteveFroehlich, @gubi, @langzhenjun, @Workster, @heseen, @Kingparis1, @jeanlucmongrain, @claudioap, @diego-G, @immense055, @wangya123456789, @cnfanhua, @gruberdev, @iamtakagi, @spookiestevie, @demethrius20, @shaksiper, @tymon42, @Noisyboy1040, @chentianle10000, @qybo1234, @filipporomani, @root-couture, @httppedro, @Boneflame, @zoulx32, @patimapoochai, @thisispalash, @worldwidebaby, @privyack, @cljunior, @colahui, @twainQAQ, @dnorac, @wcicada, @Necklaces, @Kakuye, @ivcppNucl3arSn3k, @vv01f, @Jihhn, @mskf3000, @wilbur-yu, @guanguans, @Shunbaby, @lovejackal, @lbinxianchong, @qarth, @korolr, @Sungvirat, @GitLeandroHub, @hypernormal, @fhwo13, @truseer, @TQ-Hannto, @bambino-boy, @cleett, @Ktar5, @CxxLeisure, @ziplus4, @BigaMachine, @huang5556019, @raphaelw1206, @cfgxy, @cagev, @Marcus-Arcadius, @ChandlerVer5, @xiezhaoye, @TheresaQWQ, @duckartes, @Demacr, @wangweeii, @dumblob, @chengi, @geoffmyers, @pikaciu22x, @SunflowerAries, @alechilczenko, @LuanJian, @Bllss, @iknownothing, @fyezool, @octalmage, @dongchunfeng, @ProfessorManhattan, @Mitleidleggins, @puneetkaura, @ehang233basememara, @masatatsu8, @goglor, @aisurf3r, @chengza, @ErikZhou, @pushpendrapratap, @THEAIbotOS, @deland, @OverflowCat, @chenyi14501, @ArchNad, @yanght1001, @21guns, @MICHIVEDA, @raphi-web, @humonidtyphoon, @irux, @dacoffey, @rinodrummer, @scwall, @miguel5612, @masterDisaster3, @psqnt, @monstapiece, @moitoi, @estimated1337, @phnsh, @onuratakan, @SirTerrific, @xiaojinxiansheng, @paolouma, @xdark21, @Workster, @5l1v3r1, @mj-vn, @goalall, @pedrosantos867, @chicoarts, @Maoye74, @xillwill24, @taw420, @akirayamamoto, @ZhihaoJun, @ethanhust, @lxy1992, @no-name2017, @LYLsGit, @arvinmoj, @Raselmahfuzchowdurywestinyang, @ThatXliner, @KaiDevrim, @picospuch, @WuDier, @liujifight, @todoleza, @sdpinpdx, @Timur2915, @sbmsr, @1000heads-luke, @thdaraujo, @nonomal, @devaneatshit, @camsiabor, @guangrei, @huiyifyj, @rucas, @zoulx32, @liuxingpluck, @ruskid, @theerfan, @yobi144, @guilhermesmartins, @ode233, @consuellam, @ii64, @songproducer, @lyf1350, @RickyC0626, @QuBotao, @Aithoagon, @Abdi-Adan, @horrrt, @Sunflower-V, @qimmiq, @ludbek, @hangu1116, @ndaidong, @sorairolake, @YanCore, @slevi123, @PINKONG, @Sunzijie, @thatfiredev, @ecodjtal, @heygema, @fedefloris, @xiaotian044500, @nguyenchicuongvnyonghi, @elevate420, @dnlcrl, @modulexcite, @CTNeptune, @SiNaPsEr0x, @44667788, @Edmunddz, @ihor-nahuliak, @lovezzzxxx, @taw420, @itimflint, @chenbaih, @arvinmoj, @UmutAlihan, @TAWABAMI, @omaidb, @Radtoo, @EthanLuu, @iaxat, @biadasiewicz, @timurturbil, @srqcg, @larryzxq705, @Irischen666, @Laurenfrost, @divyanshu013, @Dadogg80, @carlosb1, @richstokes, @kr1sp1n, @CJJKKK, @Null-SID, @smarty-kiki, @cn-kali-team, @Boni153, @toutpuissantged, @f4bio, @dbgb, @kozyilmaz, @guodroid, @wifiwang777, @smartgrids, @hansuke, @proabhishek, @comeUpWithItLater, @amazzoccone, @Roeis, @willxuecn, @FutureInfinityraidel-a, @dbgb, @pcarolei, @mejohnny, @THISISAGOODNAME, @rinodrummer, @dasferco, @dnorac, @JearyCheung, @trsxnn, @charlesbarr, @nguyenkvvn, @thatsmystapler, @Nable80, @zhutianwei, @kangjian-haha, @Logicxcz, @dogdogeating, @gonzaloperin, @huangjinbo, @work4life2, @li494391537, @liuifan, @Boni153, @Priyanshu79, @greatshi, @DreamWalkerXZ, @legomushroom, @nardonykolyszyn, @realcapobambino, @EvanHon1818, @mope, @iverbitskii, @arthurzinck, @alex016688, @Hessenberg, @zu1k, @Nightmare-Serene, @RikuMyo, @samihda, @coolgreenhat, @Kyron33, @Galiold, @lpcanh, @NanamiMio, @matejkramny, @ZeroHackz, @peer2poor, @mrweisz, @Allumnyrizkyaners, @spartucus, @lixiaoyu0611, @tyndallm, @AlanRayburn, @Marravillas, @namezheqian, @jeffy5, @yajiya, @lifa123, @ali-master, @ooooevan, @Ultra980, @Ledjob, @Pegasus-E, @sTorro, @SiNaPsEr0x, @thatfiredev, @daturadev, @changhaottt, @muszka95, @jeeinn, @Erth616, @RibaCamabuto, @JiezengDev, @vaxin, @lovealan, @terrydash, @deepserket, @dannyxddd, @MC-Kaden, @Tayeb-Ali, @TQ-Hannto, @letuskillba, @iranadu, @Perf5150, @maacpiash, @ue5377, @Gerard19742608jourdain, @gegw, @lstarkgv, @bedevilled00-tek, @sushant3095, @askides, @wnma3mz, @elgrillo50Guille, @williamdes, @v1ctorf, @tangtang233, @rockmarques

**Comment by josuecv26** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kodjosama, @hMihaiDavid, @Crypto-Spartan, @aarongwest, @jkwroi24io9342fsdjklAdf, @Pinerain, @zcieng, @AvichalChadha, @ThomasK33, @Mosney, @1d0n7kn0w, @CreeperFace00, @streamsteel, @marcialwushu, @nardonykolyszyn, @Mryasiralam87, @ThatNerdUKnow, @InfoDefenseResearch, @wusertu, @lfzawacki, @Alicebond, @Hxixing, @IPjoshua, @liuyukuai, @Thomas-on-Mars, @Apaurusaya, @5aharsh, @ZegJoker, @javadnikbakht, @jmmd83, @wunscheswx, @Angle-bo, @stevexyh, @Brightfl, @shino49, @andrewratliff, @CyrilNb, @Gumbraise, @dmtrl, @nixnfg, @onanying, @ZeroKill1024, @hanyoujun, @JadyLiu98, @MarcinSoj, @ilyydy, @sp0oks, @Dwdeath, @Werve, @feccruzrucas, @wangke0809, @destshadow, @dont32, @qarth, @Ziur02, @tanneberger, @dut3062796s, @sanjaydatasciencedojo, @mrh1377, @akay, @manassingh2611, @badr-elmazaz, @ReanSn0w, @lsgalves, @barisaksu, @KuNgia09, @Alicebond, @xy-cypher, @anilyagiz, @i4irsh, @nekohands, @Gum-Joe, @alxkhr, @Yetgear, @qrxnz, @pakholeung37, @yhlzkd, @Stmol, @jaredwolff, @jd1xon, @ebwood, @theerfan, @loper-deve, @uadp, @smartgrids, @CRYP70N1C4, @SingTingTech, @pshoferus, @Taithrah, @HideUsSaveUs, @jamestang1016, @DarkmatterVale, @kxw1059, @0987031613dow, @CirceSky, @AmirAlter0, @gaojunming, @adminsharmasecureservicescausa, @R4yGMparlox, @wsk2007, @bavuongco10, @hueyy, @TCD-Brendan, @NullpointerWorks, @Ca11back, @IsaacQiang, @zl03134, @bt-life, @araguaci, @jetwong88, @latenightz, @navitux, @bhargavaman, @nguyenchicuongvn, @dkiziridis, @viralhysteria, @ChristopheBougere, @marcofavorito, @UmutAlihan, @User-Hrsat, @pm1122, @u-u-z, @aleatory-avers, @interlab, @langzhenjun, @holymonity, @xznhj8129, @legomushroom, @johnnyknoxville1337, @jiujiwuan, @reducm, @patrickoliveras, @busyluo, @wainola, @maxguru, @lunarcontrol, @jiebiantiaoqu, @ZKing1000, @martinadamsdev, @pun-var, @yobi144, @weiqilin66, @primexiao, @hjcccompany, @trimechee, @martin-sweeny, @anilyagiz, @barisaksuFluffyPanda69, @greatshi, @drelinx, @keef1212, @Jefferderp, @hasansaikat, @AsakuraMizu, @shino49, @EMAN6, @sonix07, @sahad752, @ViralNexus, @LuisHCK, @ACRutkovsky, @elevate420, @kursemaster, @Necklaces, @aleatory-avers, @guicbrito, @Pagliacii, @0-yy-0, @aeblyve, @Slins-23, @owlietwo, @wzqHaoShuai, @mallikarjunasai995, @okibcn, @lynther, @whylovejp, @YuzeTT, @galaris, @iemadk, @Escanor767, @Satharus, @sreyaschaithanya, @digglesworth, @jeuskirchen, @jsmette, @yixvan6, @w1kke, @shujunqiao, @Illusion5103, @foreandr, @occoder, @yannicka, @hepengfei5709, @Mybrc91, @Herbling101, @cosminstn, @simonewebdesignalbertjimenez, @drinks5, @HDark15, @PadLex, @erickRiquelme, @Yazawazi, @xiuxiubiu, @pineappleiceberg, @zedisdog, @hyphen249, @Bond198, @hansuke, @JuPlutonic, @BreakfastNow, @nobsu, @R1skNt, @jamiedevsandbox, @immime, @mongoloidkhulmikuki366385, @triceraptawr, @rinodrummer, @sergeysedoy97, @nerawzz, @sophieforceno, @jjzazuet, @langzhenjun, @TheWeirdDev, @Hollytryx, @the-sarge, @seangcs27, @zeros-origin, @baizhi1989, @nhatthaiquang-agilityio, @44667788, @nobiit, @cheeseonfifth, @intnetfarmer, @chaorenex1, @Cale318, @loongdy, @lucasb, @Gronghon, @Chen0x00, @sixoneone, @jd1xon, @MarcinSoj, @Deondutoit94, @jackz314, @kevenfrank33, @textfoowatson1101, @lizhangwen1024, @broker, @JaydeepGo, @LongBaoLee, @umm233, @ubertidavide, @galaris, @xcryptoshadow, @Allumny, @ppok, @jsksxs360, @Frederic-Zhou, @efranelas, @, @buxiaoyang, @smxll, @eman613, @Pereira-Araujo, @ShiSheng233, @basilhe, @yixvan6, @HarpyX, @a17, @hlwanhoj, @PotterLee694, @zwlyn, @QuBotao, @therealt3nzin, @rldotai, @BlackNurse, @phobos-dthorga, @stonesee, @CnYeSheng, @cheezberg, @bubblesthebear, @JadyLiu98, @bronyem, @pH-7, @81pla, @ptruser, @Tahax09, @Beyazatli, @zvooz, @tifDev, @machavia, @aisurf3r, @mcthesw, @MmrDev, @Carrotor116efranelas, @DJOCKER-FACE, @racinette, @hijierui, @asmexcaliburwoods, @suikodev, @holld, @andylee1890, @TeslowMusic, @mac-code, @snowyu, @nextkitt, @serousoma, @ahmedmaher05, @andreichernov, @krystofair, @dasferco, @mikoim, @rppf, @MEGATRONGOD, @egbulsoni, @eliocean, @ddowse, @gruberdev, @andylin2008, @LianSheng197, @academ1c, @Archor-btw, @horacioars, @ziceweek, @genIoco, @pikaciu22x, @cmingxu, @duyongbo520, @1d0n7kn0w, @junj1e, @bartmika, @leandronb, @Remulos, @MICHIVEDA, @icepuma, @JiangWei2506, @tomaszmalik, @pcranaway, @daydaychen, @gamaged, @muxiaobai, @SandeepGusain, @KuNgia09, @smrsan

**Pull request merged**
